### PR TITLE
Keybinding system

### PR DESCRIPTION
**Pull request by Yuki-Codes**
this change implements a keybinding system for arbitrary keyboard shortcuts.

image

Input events are defined in an enum: `KeyBindEvents` and Bindings are stored in the `InputConfiguration` within the configuration file. The `InputService ` handles checking the KeyBindEvents state and looking up their bindings from the configuration.

Key input is handled from the `IKeyState` service, which is a Dalamud wrapper around the game's input states, so will be cross-platform wherever Dalamud and the game are.

Unfortunately, while the VirtualKey codes for the Left and Right variants of Shift, Control, and Alt (Menu) exist, they don't hold real values, so we will lose the ability to differentiate between left and right modifiers for bindings here. (however, it turns out that Right-Control in ImGUI here doesn't work anyway, so...)

The default bindings are:
```
Toggle Brio Window - Control + B
Increment small Modifier - None
Increment Large Modifer - None
Disable Gizmo Overlay - Shift
Disable Skeleton Overlay - Control
Hide Overlay - Alt
```
we can change these before shipping in the `InputConfiguration` class.

### CODE REVIEW

**Comment by Minmoose** [comment]
I want to wait to merge this until more key-bindings are added, I also want to change the UX for the KeybindEditor tab a bit.

**Comment by Yuki-Codes** [comment]
sounds good, the editor is pretty basic.
it would be nice to have a "press any key" listening state that can just listen for whatever keys to be pushed. 🤔 

I'll start adding more keybindings, since there are a few I can think of. 👍

**Comment by Yuki-Codes** [comment]
I've added keybinds for ToggleOverlay (Ctrl+O) Undo (Ctrl+Z) and Redo (Ctrl+Y) but to hook them up correctly I also added a OnSelected/OnDeselected methods to Entities, and OnEntitySelected/OnEntityDeselected methods to Capabilities to handle attaching and detaching the input events so they only run on the selected entity posing capability. let me know if that was the right way forwards there. ❓

**Comment by Yuki-Codes** [comment]
I've just pushed a change that adds a 'prompt' overlay to the corner of the screen in GPose:
image

and an option to disable it:
image

let me know if this is something we want to keep, or else we can just ditch it when we want to merge in. 🤷‍♀️

**Pull request merged**
