### PR TITLE
ImBrio Gizmo implementation

### PR DESCRIPTION
**Pull request by Yuki-Codes**
a complete custom rotation gizmo to replace ImGuizmo rotations.

gizmo

Features:
- **Complete customization**: we can expose the axis colors, line thickness, mouse distance, etc to user settings. (see `ImBrioGizmo.Style`)
- **No reverse-angle snapping**: drag is performed on a line originating from the vector of the grabbed axis circle, so moving the cursor in a straight line will continue to rotate (this is how it works in Unity, and not how it worked in ImGuizmo or Anamnesis' gizmo)
- **More feedback**: mouse hover and down states are drawn over the gizmo
- **No popup**: ImGuizmo uses a popup window for its drag overlay, which behaves weirdly in multi-monitor setups

### CODE REVIEW

**Comment by Yuki-Codes** [comment]
this implementation is missing the world-space support.

**Comment by Yuki-Codes** [comment]
Fixed those issues. 👍

**Comment by Minmoose** [comment]
I like the change, the Gizmo is more responsive and in general seems to be easier to use, but there seems to be a problem when moving the game camera. see attached video.

https://github.com/Etheirys/Brio/assets/12839703/1081e24a-330c-4d06-8f81-ba14509a2191

**Comment by Yuki-Codes** [comment]
hmm, I actually cant get mine to do that. 🤔 

how are you moving the game camera?

**Comment by Minmoose** [comment]
> hmm, I actually cant get mine to do that. 🤔

Oh strange... 

> how are you moving the game camera?

By holding right click and moving the mouse

**Comment by Yuki-Codes** [comment]
odd. I cant get it to happen, but I think I know the solution regardless, can you give it a try with latest?

**Comment by Minmoose** [comment]
Fantastic that has fixed it, trying to think why I had this but you didn't has me a bit stumped, I wonder if it this had something to do with display drivers, but that seems weird if it is, stranger things have happened with display drivers though.

**Pull request merged**
