### PR TITLE
UI Refresh Contributions

### PR DESCRIPTION
**Pull request by Yuki-Codes**
Cleaned up main window toolbar, and posing graphical window:
image

### CODE REVIEW

**Comment by Yuki-Codes** [comment]
tweaked the layout of the DragFloat3 control to fix padding and put the expanded area inside a child frame:
image

**Comment by Yuki-Codes** [comment]
Improved the drawing of bones:
image

Added branch hover and branch selected drawing too:
bones

**Comment by Yuki-Codes** [comment]
I've added a bone selection heuristic that helps with selecting bones that are close together, and massively increased the radius at which bones can be selected, which helps with quickly selecting the desired bone.
the bone that is the closest to the mouse cursor will be selected, regardless of what order they are drawn in:
boneHover

**Comment by Minmoose** [comment]
There is a crash occurring when moving/resizing the advanced posing window, and there are also issues with padding & margin on some of the custom controls when using the default Dalamud theme.

I've seen some compatibility problems with Dalamud themes, and given our extensive use of custom controls, I think creating a dedicated ImGUI's style for Brio that would completely override the Dalamud theme with the ability to customize the style within Brio’s settings, is the best way to minimize compatibility problems.

**Comment by Yuki-Codes** [comment]
hmm, I don't get a crash when resizing my window, can you get any more information out of that?

**Comment by Yuki-Codes** [comment]
I've gone through and fixed any instances of alignment bugs I could find in the default dalamud style: 
image

I don't like the default dalamud style, but I do like having my custom style, so if possible I'd like to still support style changes. 🤔

**Comment by Yuki-Codes** [comment]
fyi: this is the custom style I use, based on Material Design, in case anybody wants it. 😉 

image

```DS1H4sIAAAAAAAACq1YS3PbNhD+Kx2e2hnXgwcJkLrFcRof4k4mdidNb7QEy6xpUaUoO47H/z0LErsAISmR7J6oBff79oHFcqGnpEwm/JgdJVfJ5Cn5O5koK3zpn89HyTSZaLswc1rGaTGnxY4z0LqGt0fJPJmkdvnG6VZOLq/cwr8OnDqw7E3cuoXasd5FWmmvtdi62mxdXbpV4VZFv/of/OjdaMGd/tXKATt405teu4V793xwz6/OtUeKPgui/7aRE2uuLN2yHEU7bSDOp+TSfO3ce+7e989/3PNz/wR9q3harcqr2sy8dcYLxXL0ASUABxJRfK4Ws+bhZE5wLoqUc60dnossLZhweP+SCN7eVPUsxLNUqEwWiCdxICCRCD42y/UyIGB5kWVCCEwXiT2BF4ngpGlnpvUOaKa4YuQAiYMDJEb4i5sSErG5W2i3B1AGAfZHW96ZMHDFdJ5K9NuLg10Sya4jOGvuTRvsnxAys2l2PF7sebwY87yZdtW9P4LC+gkmkYZnKlcCC8G/9cVUdbV5RSE4fOQGwQ4iedvUdblcBVk5kOfcLNYnZRuGg5mwPwZYGP3FtAWbVyPIrhoY6b9vbQvDpKeSSy0UJp3EIekkbpq1NBuVoBXjOR3lXswkktHL7WRxOeg0Y0WOCfSiI0MxONdmentetrdEoQspUjh+VFGp4ExpR6FEqlQuRjmtKzhYowTJImcsKzBBXuw5vLiFIwoozUWWU5cgqechyZ/xddc1i6ipsuOiGM7FqLfagupXJQHjnZFSpYXAFkPSEARKkfF4Qw495memDNvcruJ0QEGI2PddwBgX+bsLlmqW5bDvdq/MsmzLrvm5kyzU3khuoaCYUix7zjRnmcRTK7mQEvwMawSZIpcPLthPZlV9M+/barlXBF593xyPUa919zI4WAd/fQD86sQDx/8Qw1+L62a6HjX7KJi+Mnn+w2CI5bUenTbT22ox/9ia+8o8vIRnmPwcz7u7ZfcYfFSoA+NJD0ehuuk+VAuzIm2F/cH+GCzxbYDxVvoGl+LnQmYR7Kxadc0cRgeyhe0MY2K7ELuMYRsfjah2OB0aSvgxpukMu2a0mzAEDFNZ1zYLj5OYDvtjM64A+KGa3+AQbZsiZp0+nxu4T6Mx+Ecn2Ku/qX82qANCuUn9wtRm2plwWD68ONtyfto2y8uynZvu5Tx/lvdnkKF6lKWXsAz3B6jzmG53QnSEPK3ugpRg98HTPgw44I2d6ppZWQ+4/UAye7bXQ5iPk0nyZf37u0fzy6/nZWfaqqx/S+DqOty4yo1aHu/7EK7vtjgUY27C0RNuxXtoBfc1vKnhHS3QMntdA699HjRlQlMu7C/SnW9EquluFHLeBJM3jJmyoJPHRAbdeGDnxwpuUwUPfa7CNp4JlmOAWsB8x92wZWdOoZk9x4TEvwDA51zlWud4ajmMVCnMqPgBIJGgtzsSBR0w0Kr91sR7U6gwBt8U8daQbqHDeRI84gOfNxvmEv+I8F0ldRfi8T76qUPR/Vkw8lBCOkgX/rCI9hFuplts+1kMcorWiVNlYW34z05exCeqZ3eaoAofAFh9/g6OKFFrIhIAAA==```

**Pull request merged**
